# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

# MAGIC %sql
# MAGIC create schema la_crime.silver;

# COMMAND ----------

(spark.table("la_crime.silver.la_crime_silver")
 .toPandas()
 .to_csv("/Volumes/la_crime/silver/processed/la_crime_full.csv", index=False))
